### ISSUE TITLE
[建议] 管理员权限能否自定义？

### ISSUE THREAD

**Issue by aki66938** [flowerfalling/wxbot#1]
如题，出门带俩手机有点麻烦（切微信聊天也费劲），用主微信控制机器人功能的开关会不会更好点？
换言之，希望机器人的控制权可指定

**Comment by flowerfalling** [comment]
You can already transfer permissions to another account. Just fill in the nickname of the account you want to transfer to in the admin field in SusRobot after version 538b948c like this:
```python
def main() -> None:
    susbot = SusRobot(admin="nickname")
    susbot.run()
```

**Comment by aki66938** [comment]
thanks
